name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/lovelace-energy-entity-row/lovelace-energy-entity-row/dist/energy-entity-row.js
          asset_name: energy-entity-row.js
          tag: ${{ github.ref }}
          overwrite: true
  validate:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HACS Validate
        uses: hacs/action@main
        with:
          category: plugin
